bin = './sord-mO'
cores = 16
dtype = '>f4'
email = 'wangyf'
fortran_flags = {'O': ('-O3 -g', '-fimplicit-none', '-Wall', '-o'), 'p': ('-pg', '-Mprof=func', '-fimplicit-none', '-Wall', '-o'), 't': ('-Ktrap=fp', '-Mbounds', '-fimplicit-none', '-Wall', '-o'), 'g': ('-Ktrap=fp', '-Mbounds', '-Mchkptr', '-g', '-fimplicit-none', '-Wall', '-o')}
fortran_mpi = ('mpif90',)
fortran_serial = ('gfortran',)
host = 'cetuslac1'
hosts = ('wangyf',)
infiles = ()
itbuff = 10
login = 'mira.alcf.anl.gov'
machine = 'mira'
maxcores = 16
maxnodes = 22640
maxram = 65536
maxtime = (24, 0)
minnodes = 1
mode = 'm'
name = 'elastic'
nodes = 244
notes = '\naccount: jmz\n'
np = 3904
optimize = 'O'
os_ = ('Linux', 'cetuslac1', '2.6.32-573.35.2.el6.ppc64', '#1 SMP Mon Oct 24 14:00:41 EDT 2016', 'ppc64')
pmem = 32
post = ''
ppn = 16
pre = ''
prepare = True
queue = None
ram = 512
rate = 1000000.0
run = False
rundate = 'Sat Dec 31 04:46:19 2016'
rundir = '/gpfs/mira-home/wangyf/local/sord/scripts/test/elastic'
totalcores = 3904
user = 'wangyf'
walltime = '0:10:00'
