bin = './sord-sO'
cores = 1
dtype = '<f4'
email = 'yow004'
fortran_flags = {'O': ('-O3', '-fimplicit-none', '-Wall', '-Wtabs', '-Wl,-no_compact_unwind', '-o'), 'p': ('-O', '-pg', '-fimplicit-none', '-Wall', '-Wtabs', '-Wl,-no_compact_unwind', '-o'), 't': ('-fbounds-check', '-ffpe-trap=invalid,zero,overflow', '-fimplicit-none', '-Wall', '-Wtabs', '-Wl,-no_compact_unwind', '-o'), 'g': ('-fbounds-check', '-ffpe-trap=invalid,zero,overflow', '-g', '-fimplicit-none', '-Wall', '-Wtabs', '-Wl,-no_compact_unwind', '-o')}
fortran_mpi = ('mpif90',)
fortran_serial = ('gfortran',)
host = 'b98-aruba1-guest-10-110-30-179.wlan.cpp.edu'
hosts = ('igpp13grad9-2.local',)
infiles = ()
itbuff = 10
login = 'igpp13grad9-2.local'
machine = 'igpp13grad9-2.local'
maxcores = 2
maxnodes = 1
maxram = 8000000
maxtime = 0
mode = 's'
name = 'asperity'
nodes = 1
notes = '\nIGPP laptop\n\nssh -fNL localhost:8022:pisco.sdsu.edu:22 sciences.sdsu.edu\nssh -p 8022 localhost\n\nUse MPICH instead of OpenMPI:\nexport PATH="/opt/mpich2/gnu/bin:${PATH}"\n'
np = 1
optimize = 'O'
os_ = ('Darwin', 'b98-aruba1-guest-10-110-30-179.wlan.cpp.edu', '17.4.0', 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64', 'x86_64')
pmem = 319
post = ''
ppn = 1
pre = ''
prepare = True
queue = None
ram = 319
rate = 1000000.0
run = False
rundate = 'Tue Apr 24 13:02:35 2018'
rundir = '/Users/yow004/Desktop/SORDlatest/script/asperity'
totalcores = 2
user = 'yow004'
walltime = '1:00:00'
